/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'rgb(var(--color-primary-rgb) / <alpha-value>)',
        'on-primary': 'rgb(var(--color-on-primary-rgb) / <alpha-value>)',
        'primary-container': 'rgb(var(--color-primary-container-rgb) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--color-on-primary-container-rgb) / <alpha-value>)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'inverse-primary': 'var(--color-inverse-primary)',

        secondary: 'rgb(var(--color-secondary-rgb) / <alpha-value>)',
        'on-secondary': 'rgb(var(--color-on-secondary-rgb) / <alpha-value>)',
        'secondary-container': 'rgb(var(--color-secondary-container-rgb) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--color-on-secondary-container-rgb) / <alpha-value>)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',

        tertiary: 'rgb(var(--color-tertiary-rgb) / <alpha-value>)',
        'on-tertiary': 'rgb(var(--color-on-tertiary-rgb) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--color-tertiary-container-rgb) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--color-on-tertiary-container-rgb) / <alpha-value>)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',

        error: 'rgb(var(--color-error-rgb) / <alpha-value>)',
        'on-error': 'rgb(var(--color-on-error-rgb) / <alpha-value>)',
        'error-container': 'rgb(var(--color-error-container-rgb) / <alpha-value>)',
        'on-error-container': 'rgb(var(--color-on-error-container-rgb) / <alpha-value>)',

        background: 'rgb(var(--color-background-rgb) / <alpha-value>)',
        'on-background': 'rgb(var(--color-on-background-rgb) / <alpha-value>)',

        surface: 'rgb(var(--color-surface-rgb) / <alpha-value>)',
        'surface-dim': 'rgb(var(--color-surface-dim-rgb) / <alpha-value>)',
        'surface-bright': 'rgb(var(--color-surface-bright-rgb) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--color-surface-container-lowest-rgb) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--color-surface-container-low-rgb) / <alpha-value>)',
        'surface-container': 'rgb(var(--color-surface-container-rgb) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--color-surface-container-high-rgb) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--color-surface-container-highest-rgb) / <alpha-value>)',
        'on-surface': 'rgb(var(--color-on-surface-rgb) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--color-on-surface-variant-rgb) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--color-inverse-surface-rgb) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--color-inverse-on-surface-rgb) / <alpha-value>)',
        'surface-variant': 'rgb(var(--color-surface-variant-rgb) / <alpha-value>)',
        'surface-tint': 'rgb(var(--color-surface-tint-rgb) / <alpha-value>)',

        outline: 'rgb(var(--color-outline-rgb) / <alpha-value>)',
        'outline-variant': 'rgb(var(--color-outline-variant-rgb) / <alpha-value>)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'gutter': '16px',
        'touch-target-min': '44px',
        'edge-padding-mobile': '16px',
        'edge-padding-desktop': '24px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};